apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: test-onesixinstaller-chatbot
  janus-idp.io/tekton: test-onesixinstaller-chatbot
  backstage.io/kubernetes-id: test-onesixinstaller-chatbot
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: test-onesixinstaller-chatbot
resources:
  - application-dev.yaml