apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: test-onesixinstaller-chatbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-onesixinstaller-chatbot
  name: test-onesixinstaller-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
